package main

import (
	"fmt"
	"io"
	"strings"
)

// generateCode writes Go struct definitions for a template schema.
func generateCode(w io.Writer, pkg string, schema *templateSchema, opts genOptions) {
	fmt.Fprintf(w, "// Code generated by handlebars-gen. DO NOT EDIT.\n")
	fmt.Fprintf(w, "package %s\n\n", pkg)

	if opts.validate {
		fmt.Fprintf(w, "import (\n")
		fmt.Fprintf(w, "\t\"fmt\"\n")
		fmt.Fprintf(w, "\t\"strings\"\n")
		fmt.Fprintf(w, ")\n\n")
	}

	writeStruct(w, schema.TypeName, schema.Fields, opts, 0)

	if opts.validate {
		writeValidateFunc(w, schema)
	}
}

type genOptions struct {
	jsonTags       bool
	handlebarsTags bool
	validate       bool
}

func writeStruct(w io.Writer, name string, fields map[string]*fieldInfo, opts genOptions, depth int) {
	sorted := sortedFields(fields)

	fmt.Fprintf(w, "type %s struct {\n", name)
	for _, f := range sorted {
		goType := goTypeStr(f, name)
		tags := buildTags(f, opts)
		fmt.Fprintf(w, "\t%s %s%s\n", f.Name, goType, tags)
	}
	fmt.Fprintf(w, "}\n\n")

	// Write child structs
	for _, f := range sorted {
		if (f.Type == typeStruct || f.Type == typeSlice) && len(f.Children) > 0 {
			childName := name + f.Name
			writeStruct(w, childName, f.Children, opts, depth+1)
		}
	}
}

func goTypeStr(f *fieldInfo, parentName string) string {
	switch f.Type {
	case typeSlice:
		if len(f.Children) > 0 {
			return "[]" + parentName + f.Name
		}
		return "[]interface{}"
	case typeStruct:
		if len(f.Children) > 0 {
			return parentName + f.Name
		}
		return "map[string]interface{}"
	case typeInterface:
		return "interface{}"
	default:
		return "string"
	}
}

func buildTags(f *fieldInfo, opts genOptions) string {
	var tags []string

	if opts.jsonTags {
		tags = append(tags, fmt.Sprintf(`json:"%s"`, f.JSONName))
	}
	if opts.handlebarsTags && f.JSONName != strings.ToLower(f.Name) {
		tags = append(tags, fmt.Sprintf(`handlebars:"%s"`, f.JSONName))
	}

	if len(tags) == 0 {
		return ""
	}
	return " `" + strings.Join(tags, " ") + "`"
}

func writeValidateFunc(w io.Writer, schema *templateSchema) {
	fmt.Fprintf(w, "// Validate checks that all required fields are present and non-empty.\n")
	fmt.Fprintf(w, "func (d %s) Validate() error {\n", schema.TypeName)
	fmt.Fprintf(w, "\tvar missing []string\n")

	sorted := sortedFields(schema.Fields)
	for _, f := range sorted {
		if !f.Required {
			continue
		}
		writeFieldValidation(w, f, "d", "")
	}

	fmt.Fprintf(w, "\tif len(missing) > 0 {\n")
	fmt.Fprintf(w, "\t\treturn fmt.Errorf(\"missing required fields: %%s\", strings.Join(missing, \", \"))\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "\treturn nil\n")
	fmt.Fprintf(w, "}\n")
}

func writeFieldValidation(w io.Writer, f *fieldInfo, accessor string, prefix string) {
	fieldAccess := accessor + "." + f.Name
	fieldPath := prefix + f.JSONName

	switch f.Type {
	case typeString:
		fmt.Fprintf(w, "\tif %s == \"\" {\n", fieldAccess)
		fmt.Fprintf(w, "\t\tmissing = append(missing, %q)\n", fieldPath)
		fmt.Fprintf(w, "\t}\n")
	case typeInterface:
		fmt.Fprintf(w, "\tif %s == nil {\n", fieldAccess)
		fmt.Fprintf(w, "\t\tmissing = append(missing, %q)\n", fieldPath)
		fmt.Fprintf(w, "\t}\n")
	case typeSlice:
		fmt.Fprintf(w, "\tif %s == nil {\n", fieldAccess)
		fmt.Fprintf(w, "\t\tmissing = append(missing, %q)\n", fieldPath)
		fmt.Fprintf(w, "\t}\n")
	case typeStruct:
		// For structs, just check nested required fields
		for _, child := range sortedFields(f.Children) {
			if child.Required {
				writeFieldValidation(w, child, fieldAccess, fieldPath+".")
			}
		}
	}
}
